character:
  job: 游侠
  level:
    base: 140
    job: 80
  quality:
    str: 15
    agi: 171
    vit: 35
    int: 43
    dex: 287
    luk: 83
  detectByPanel: #根据面板来预测装备攻击/装备防御
    atk: 3836 #面板物理攻击
    def: 528 #面板物理防御
    matk: 1120 #面板魔法攻击
    mdef: 424 #面板魔法防御
  profits:
    general:
      critical: 42 #暴击
      criticalDamage: 25.6 #暴伤%
      criticalResist: 20 #暴击防护
      criticalDamageResist: 0 #爆伤减免%
      ordinary: 0 #普攻攻击力
      ordinaryDamage: 2 #普攻伤害加成%
      ordinaryResist: 0 #普攻伤害减免%
      skill: 0 #技能伤害加成%
      skillResist: 5 #技能伤害减免%
      mvp: 0 #MVP增伤%
      mvpResist: 0 #MVP减伤%
    physical: #物理属性
      spike: 0.4 #物理穿刺
      attackPer: 20 #物理攻击%
      defencePer: 5 #物理防御%
      damage: 0 #物伤加成%
      ignore: 0 #忽视物防%
      resist: 0 #物伤减免%
      nearResist: 0 #近战物理伤害减免%
      remoteResist: 0 #远程物理伤害减免%
      refine: 101 #精炼物攻
      refineResist: 0 #精炼物免%
    magical: #魔法属性
      spike: 0 #魔法穿刺
      attackPer: 19 #魔法攻击%
      defencePer: 9 #魔法防御%
      damage: 0 #魔伤加成%
      ignore: 0 #忽视魔防%
      resist: 2 #魔伤减免%
      refine: 84 #精炼魔攻
      refineResist: 0 #精炼魔免%
    refine: #装备和首饰精炼等级
      weapon: 0
      ring1: 0
      ring2: 0
    natureAttack: #属性-技能增强
      风: 0
      地: 0
      火: 9
      水: 1
      无: 0
      圣: 6
      暗: 0
      念: 0
      毒: 0
      不死: 0
    natureDamage: #属性-攻击增加
      风: 6
      地: 7
      水: 8
      火: 7
      无: 0
      圣: 6
      暗: 0
      念: 2
      毒: 1
      不死: 0
    natureResist: #属性-伤害减免
      风: 0
      地: 2
      火: 0
      水: 10
      无: 1
      圣: 0
      暗: 4
      念: 0
      毒: 0
      不死: 0
    raceDamage: #种族-攻击增加
      动物: 4.2
      人形: 1.2
      恶魔: 2.2
      植物: 0.2
      不死: 6.2
      无形: 0.2
      鱼贝: 5.2
      天使: 0.2
      昆虫: 13.2
      龙: 2.2
    raceResist: #种族-伤害减免
      动物: 2.2
      人形: 0.2
      恶魔: 1.2
      植物: 0.2
      不死: 4.2
      无形: 0.2
      鱼贝: 0.2
      天使: 0.2
      昆虫: 0.2
      龙: 0.2
    shapeDamage: #体型-攻击增强
      小型: 0
      中型: 0
      大型: 0
    shapeResist: #体型-伤害减免
      小型: 0
      中型: 0
      大型: 0
