character:
  job: 群星猎手
  level:
    base: 170
    job: 80
  quality:
    str: 116
    agi: 179
    vit: 74
    int: 135
    dex: 363
    luk: 244
  detectByPanel: #根据面板来预测装备攻击/装备防御
    atk: 14269 #面板物理攻击
    def: 3623 #面板物理防御
    matk: 3106 #面板魔法攻击
    mdef: 1941 #面板魔法防御
  profits:
    general:
      critical: 109 #暴击
      criticalDamage: 131.1 #暴伤%
      criticalResist: 68 #暴击防护
      criticalDamageResist: 0 #爆伤减免%
      ordinary: 0 #普攻攻击力
      ordinaryDamage: 12.9 #普攻伤害加成%
      ordinaryResist: 4.5 #普攻伤害减免%
      skill: 0 #技能伤害加成%
      skillResist: 0 #技能伤害减免%
      mvp: 2 #MVP增伤%
      mvpResist: 2 #MVP减伤%
    physical: #物理属性
      spike: 47 #物理穿刺
      attackPer: 75.5 #物理攻击%
      defencePer: 47 #物理防御%
      damage: 47.9 #物伤加成%
      ignore: 69.5 #忽视物防%
      resist: 29 #物伤减免%
      nearResist: 0 #近战物理伤害减免%
      remoteResist: 0 #远程物理伤害减免%
      refine: 1671 #精炼物攻
      refineResist: 32.4 #精炼物免%
    magical: #魔法属性
      spike: 0 #魔法穿刺
      attackPer: 40 #魔法攻击%
      defencePer: 42 #魔法防御%
      damage: 8 #魔伤加成%
      ignore: 1.5 #忽视魔防%
      resist: 12 #魔伤减免%
      refine: 48 #精炼魔攻
      refineResist: 16.8 #精炼魔免%
    refine: #装备和首饰精炼等级
      weapon: 10
      ring1: 10
      ring2: 15
    natureAttack: #属性-技能增强
      风: 28.2
      地: 17.2
      火: 36.2
      水: 23.2
      无: 0
      圣: 6
      暗: 0
      念: 10.7
      毒: 20
      不死: 0
    natureDamage: #属性-攻击增加
      风: 8
      地: 7
      水: 80
      火: 7
      无: 0
      圣: 6
      暗: 3
      念: 1
      毒: 1
      不死: 0
    natureResist: #属性-伤害减免
      风: 4
      地: 5
      火: 5
      水: 30
      无: 0
      圣: 0
      暗: 4
      念: 0
      毒: 5
      不死: 0
    raceDamage: #种族-攻击增加
      动物: 11.9
      人形: 19.6
      恶魔: 13.9
      植物: 11.9
      不死: 20.9
      无形: 11.9
      鱼贝: 17.9
      天使: 11.9
      昆虫: 20.9
      龙: 13.9
    raceResist: #种族-伤害减免
      动物: 10.6
      人形: 12.6
      恶魔: 9.6
      植物: 8.6
      不死: 12.6
      无形: 8.6
      鱼贝: 8.6
      天使: 8.6
      昆虫: 8.6
      龙: 8.6
    shapeDamage: #体型-攻击增强
      小型: 0
      中型: 0
      大型: 0
    shapeResist: #体型-伤害减免
      小型: 1
      中型: 0
      大型: 1