character:
  job: 世界圣盾
  level:
    base: 170
    job: 70
  quality:
    str: 103
    agi: 131
    vit: 402
    int: 196
    dex: 78
    luk: 42
  profits:
    physical:
      #      attack: 0
      attackPer: 31
      spike: 37
      damage: 70.5
      #      refine: 0
      #      critical: 0
      #      criticalPer: 0
      #      defence: 0
      defencePer: 112.5
      #      resist: 0
    magical:
      #      attack: 0
      attackPer: 31
      spike: 5
      #      damage: 0
      #      refine: 0
      #      critical: 0
      #      criticalPer: 0
      #      defence: 0
      defencePer: 60
    #      resist: 0
    damage:
      #      skill: 0
      mvp: 28
    natureAttack: #属性攻击%
      无: 2
      地: 20
      风: 21
      水: 1
      火: 21
      圣: 28
    #      暗: 0
    #      不死: 0
    #      念: 0
    #      毒: 0
    raceDamage: #种族增伤%
      无形: 4
      人形: 26.7
      植物: 3
      动物: 22
      昆虫: 16
      鱼贝: 9
      天使: 3
      恶魔: 15
      不死: 22
      龙: 5
    raceResist: #种族减伤%
    #      无形: 0
    #      人形: 0
    #      植物: 0
    #      动物: 0
    #      昆虫: 0
    #      鱼贝: 0
    #      天使: 0
    #      恶魔: 0
    #      不死: 0
    #      龙: 0
    shapeDamage: #体型增伤%
      小型: 65
      中型: 6
      大型: 55
    shapeResist: #体型减伤%
    natureDamage: #属性增伤%
      #      无: 0
      地: 6
      风: 8
      水: 10
      火: 7
      圣: 6
      暗: 2
      #      不死: 0
      #      念: 0
      毒: 1
    natureResist: #属性减伤%
  detectByPanel: #根据面板预测: 装备攻击/装备防御
    atk: 0
    def: 7766
    matk: 0
    mdef: 3308
