character:
  job: 世界圣盾
  level:
    base: 170
    job: 80
  quality:
    str: 130
    agi: 131
    vit: 399
    int: 196
    dex: 78
    luk: 42
  detectByPanel: #根据面板来预测装备攻击/装备防御
    atk: 8052 #面板物理攻击
    def: 8212 #面板物理防御
    matk: 4587 #面板魔法攻击
    mdef: 3308 #面板魔法防御
  profits:
    general:
      critical: 16 #暴击
      criticalDamage: 34.2 #暴伤%
      criticalResist: 47 #暴击防护
      criticalDamageResist: 31.5 #爆伤减免%
      ordinary: 0 #普攻攻击力
      ordinaryDamage: 0 #普攻伤害加成%
      ordinaryResist: 12 #普攻伤害减免%
      skill: 0 #技能伤害加成%
      skillResist: 6 #技能伤害减免%
      mvp: 0 #MVP增伤%
      mvpResist: 0 #MVP减伤%
      noMvp: 0 #普通魔物增伤%
      noMvpResist: 0 #普通魔物减伤%
      moveSpeed: 145 #移动速度%
      attackSpeed: 261.1 #攻击速度%
    physical: #物理属性
      attack: 5695 #攻击
      defence: 3259 #防御
      spike: 37 #物理穿刺
      attackPer: 31 #物理攻击%
      defencePer: 124.5 #物理防御%
      damage: 70.5 #物伤加成%
      nearDamage: 0 #近战物理伤害%
      remoteDamage: 0 #远程物理伤害%
      ignore: 178.1 #忽视物防%
      resist: 41.7 #物伤减免%
      nearResist: 13.4 #近战物理伤害减免%
      remoteResist: 25 #远程物理伤害减免%
      refine: 934 #精炼物攻
      refineResist: 38.7 #精炼物免%
    magical: #魔法属性
      attack: 2726 #攻击
      defence: 1872 #防御
      spike: 5 #魔法穿刺
      attackPer: 31 #魔法攻击%
      defencePer: 60 #魔法防御%
      damage: 0 #魔伤加成%
      ignore: 11.5 #忽视魔防%
      resist: 70 #魔伤减免%
      refine: 286 #精炼魔攻
      refineResist: 32 #精炼魔免%
    refine: #装备和首饰精炼等级
      weapon: 10
      ring1: 0
      ring2: 8
    natureAttack: #属性-技能增强
      风: 21
      地: 20
      火: 21
      水: 1
      无: 2
      圣: 28
      暗: 0
      念: 0
      毒: 0
      不死: 0
    natureDamage: #属性-攻击增加
      风: 8
      地: 6
      水: 10
      火: 7
      无: 0
      圣: 6
      暗: 2
      念: 0
      毒: 1
      不死: 0
    natureResist: #属性-伤害减免
      风: 16
      地: 2
      水: 10
      火: 3
      无: 7.5
      圣: 50
      暗: 14
      念: 0
      不死: 10
      毒: 15
    raceDamage: #种族-攻击增加
      动物: 22
      人形: 26.7
      恶魔: 15
      植物: 3
      不死: 22
      无形: 4
      鱼贝: 9
      天使: 3
      昆虫: 16
      龙: 5
    raceResist: #种族-伤害减免
      动物: 5
      人形: 7
      恶魔: 14
      植物: 3
      不死: 17
      无形: 3
      鱼贝: 3
      天使: 3
      昆虫: 3
      龙: 3
    shapeDamage: #体型-攻击增强
      小型: 65
      中型: 6
      大型: 55
    shapeResist: #体型-伤害减免
      小型: 31
      中型: 6
      大型: 0
