character:
  job: 暴君
  level:
    base: 170
    job: 80
  quality:
    str: 63
    agi: 226
    vit: 97
    int: 56
    dex: 342
    luk: 221
  detectByPanel: #根据面板来预测装备攻击/装备防御
    atk: 18567 #面板物理攻击
    def: 4433 #面板物理防御
    matk: 4578 #面板魔法攻击
    mdef: 2508 #面板魔法防御
  profits:
    general:
      critical: 90 #暴击
      criticalDamage: 68.2 #暴伤%
      criticalResist: 82 #暴击防护
      criticalDamageResist: 0 #爆伤减免%
      ordinary: 0 #普攻攻击力
      ordinaryDamage: 10 #普攻伤害加成%
      ordinaryResist: 0 #普攻伤害减免%
      skill: 12 #技能伤害加成%
      skillResist: 0 #技能伤害减免%
      mvp: 3 #MVP增伤%
      mvpResist: 0 #MVP减伤%
      noMvp: 8 #普通魔物增伤%
      noMvpResist: 0 #普通魔物减伤%
      attackSpeed: 273 #攻击速度%
      moveSpeed: 131 #移动速度%
    physical: #物理属性
      attack: 6975 #攻击
      defence: 2745 #防御
      spike: 50 #物理穿刺
      attackPer: 109 #物理攻击%
      defencePer: 56 #物理防御%
      damage: 19 #物伤加成%
      nearDamage: 0 #近战物理伤害%
      remoteDamage: 0 #远程物理伤害%
      ignore: 84.9 #忽视物防%
      resist: 25 #物伤减免%
      nearResist: 0 #近战物理伤害减免%
      remoteResist: 0 #远程物理伤害减免%
      refine: 1071 #精炼物攻
      refineResist: 32.4 #精炼物免%
    magical: #魔法属性
      attack: 2909 #攻击
      defence: 1674 #防御
      spike: 1 #魔法穿刺
      attackPer: 50 #魔法攻击%
      defencePer: 45 #魔法防御%
      damage: 0 #魔伤加成%
      ignore: 1.5 #忽视魔防%
      resist: 24 #魔伤减免%
      refine: 182 #精炼魔攻
      refineResist: 15.2 #精炼魔免%
    refine: #装备和首饰精炼等级
      weapon: 10
      ring1: 5
      ring2: 5
    natureAttack: #属性-技能增强
      风: 30
      地: 39
      火: 34
      水: 10
      无: 0
      圣: 21
      暗: 0
      念: 9
      毒: 0
      不死: 0
    natureDamage: #属性-攻击增加
      风: 23
      地: 87
      水: 10
      火: 7
      无: 0
      圣: 6
      暗: 3
      念: 0
      毒: 1
      不死: 0
    natureResist: #属性-伤害减免
      风: 19
      地: 2
      水: 10
      火: 3
      无: 11.5
      圣: 0
      暗: 4
      念: 0
      毒: 5
      不死: 0
    raceDamage: #种族-攻击增加
      动物: 28
      人形: 33.7
      恶魔: 11
      植物: 9
      不死: 18
      无形: 10
      鱼贝: 15
      天使: 9
      昆虫: 63
      龙: 11
    raceResist: #种族-伤害减免
      动物: 11
      人形: 13
      恶魔: 10
      植物: 9
      不死: 13
      无形: 9
      鱼贝: 9
      天使: 19
      昆虫: 9
      龙: 9
    shapeDamage: #体型-攻击增强
      小型: 0
      中型: 11.2
      大型: 0
    shapeResist: #体型-伤害减免
      小型: 1
      中型: 11.2
      大型: 0
