character:
  job: 神枪手
  level:
    base: 170
    job: 61
  quality:
    str: 19
    agi: 45
    vit: 22
    int: 34
    dex: 95
    luk: 26
  detectByPanel: #根据面板来预测装备攻击/装备防御
    atk: 4927 #面板物理攻击
    def: 741 #面板物理防御
    matk: 1203 #面板魔法攻击
    mdef: 406 #面板魔法防御
  profits:
    general:
      critical: 14 #暴击
      criticalDamage: 43.1 #暴伤%
      criticalResist: 6 #暴击防护
      criticalDamageResist: 0 #爆伤减免%
      ordinary: 0 #普攻攻击力
      ordinaryDamage: 0 #普攻伤害加成%
      ordinaryResist: 0 #普攻伤害减免%
      skill: 0 #技能伤害加成%
      skillResist: 0 #技能伤害减免%
      mvp: 0 #MVP增伤%
      mvpResist: 0 #MVP减伤%
    physical: #物理属性
      spike: 27 #物理穿刺
      attackPer: 22 #物理攻击%
      defencePer: 28 #物理防御%
      damage: 7.8 #物伤加成%
      ignore: 1.5 #忽视物防%
      resist: 22 #物伤减免%
      nearResist: 0 #近战物理伤害减免%
      remoteResist: 0 #远程物理伤害减免%
      refine: 204 #精炼物攻
      refineResist: 0 #精炼物免%
    magical: #魔法属性
      spike: 1 #魔法穿刺
      attackPer: 21 #魔法攻击%
      defencePer: 8 #魔法防御%
      damage: 0 #魔伤加成%
      ignore: 1.5 #忽视魔防%
      resist: 20.5 #魔伤减免%
      refine: 84 #精炼魔攻
      refineResist: 0 #精炼魔免%
    refine: #装备和首饰精炼等级
      weapon: 0
      ring1: 0
      ring2: 0
    natureAttack: #属性-技能增强
      风: 20
      地: 16.5
      火: 21
      水: 11
      无: 0
      圣: 6
      暗: 0
      念: 0
      毒: 0
      不死: 0
    natureDamage: #属性-攻击增加
      风: 6
      地: 7
      水: 8
      火: 7
      无: 0
      圣: 6
      暗: 0
      念: 2
      毒: 1
      不死: 0
    natureResist: #属性-伤害减免
      风: 0
      地: 2
      火: 0
      水: 10
      无: 1
      圣: 0
      暗: 4
      念: 0
      毒: 0
      不死: 0
    raceDamage: #种族-攻击增加
      动物: 22
      人形: 4
      恶魔: 5
      植物: 3
      不死: 9
      无形: 3
      鱼贝: 8
      天使: 3
      昆虫: 16
      龙: 5
    raceResist: #种族-伤害减免
      动物: 5
      人形: 3
      恶魔: 4
      植物: 3
      不死: 7
      无形: 3
      鱼贝: 3
      天使: 3
      昆虫: 3
      龙: 3
    shapeDamage: #体型-攻击增强
      小型: 0
      中型: 0
      大型: 0
    shapeResist: #体型-伤害减免
      小型: 0
      中型: 0
      大型: 0
