character:
  job: 神枪手
  level:
    base: 170
    job: 61
  quality:
    str: 45
    agi: 229
    vit: 34
    int: 54
    dex: 338
    luk: 216
  detectByPanel: #根据面板来预测装备攻击/装备防御
    atk: 11421 #面板物理攻击
    def: 1654 #面板物理防御
    matk: 1594 #面板魔法攻击
    mdef: 515 #面板魔法防御
  profits:
    general:
      critical: 86 #暴击
      criticalDamage: 47.9 #暴伤%
      criticalResist: 74 #暴击防护
      criticalDamageResist: 0 #爆伤减免%
      ordinary: 0 #普攻攻击力
      ordinaryDamage: 0 #普攻伤害加成%
      ordinaryResist: 0 #普攻伤害减免%
      skill: 0 #技能伤害加成%
      skillResist: 0 #技能伤害减免%
      mvp: 0 #MVP增伤%
      mvpResist: 0 #MVP减伤%
      noMvp: 18 #普通魔物增伤%
      noMvpResist: 0 #普通魔物减伤%
      attackSpeed: 224.5 #攻击速度%
      moveSpeed: 118 #移动速度%
    physical: #物理属性
      attack: 5900 #攻击
      defence: 1125 #防御
      spike: 27 #物理穿刺
      attackPer: 47 #物理攻击%
      defencePer: 43 #物理防御%
      damage: 69.7 #物伤加成%
      nearDamage: 0 #近战物理伤害%
      remoteDamage: 0 #远程物理伤害%
      ignore: 19.3 #忽视物防%
      resist: 22 #物伤减免%
      nearResist: 0 #近战物理伤害减免%
      remoteResist: 0 #远程物理伤害减免%
      refine: 1218 #精炼物攻
      refineResist: 21.6 #精炼物免%
    magical: #魔法属性
      attack: 1000 #攻击
      defence: 385 #防御
      spike: 1 #魔法穿刺
      attackPer: 41 #魔法攻击%
      defencePer: 18 #魔法防御%
      damage: 4 #魔伤加成%
      ignore: 1.5 #忽视魔防%
      resist: 21.5 #魔伤减免%
      refine: 84 #精炼魔攻
      refineResist: 12 #精炼魔免%
    refine: #装备和首饰精炼等级
      weapon: 10
      ring1: 10
      ring2: 10
    natureAttack: #属性-技能增强
      风: 55
      地: 23
      火: 28
      水: 8
      无: 0
      圣: 6
      暗: 0
      念: 3
      毒: 0
      不死: 0
    natureDamage: #属性-攻击增加
      风: 6
      地: 7
      水: 69
      火: 7
      无: 0
      圣: 6
      暗: 0
      念: 2
      毒: 1
      不死: 0
    natureResist: #属性-伤害减免
      风: 0
      地: 2
      火: 0
      水: 15
      无: 1
      圣: 0
      暗: 4
      念: 0
      毒: 0
      不死: 0
    raceDamage: #种族-攻击增加
      动物: 24.4
      人形: 6.4
      恶魔: 7.4
      植物: 5.4
      不死: 11.4
      无形: 5.4
      鱼贝: 10.4
      天使: 5.4
      昆虫: 18.4
      龙: 7.4
    raceResist: #种族-伤害减免
      动物: 7.4
      人形: 5.4
      恶魔: 6.4
      植物: 5.4
      不死: 9.4
      无形: 5.4
      鱼贝: 5.4
      天使: 5.4
      昆虫: 5.4
      龙: 5.4
    shapeDamage: #体型-攻击增强
      小型: 0
      中型: 0
      大型: 0
    shapeResist: #体型-伤害减免
      小型: 1
      中型: 0
      大型: 0
