types: 普通魔物
nature: 风
race: 动物
shape: 小型
level:
  base: 169
quality:
  str: 120
  agi: 158
  vit: 0
  int: 0
  dex: 196
  luk: 168
profits:
  general:
    criticalResist: 0 #暴击防护
    criticalDamageResist: 0 #爆伤减免%
    ordinaryResist: 0 #普攻伤害减免%
    skillResist: 0 #技能伤害减免%
  physical: #物理属性
    attack: 3445 #攻击
    defence: 2673 #防御
    defencePer: 0 #物理防御%
    resist: 50 #物伤减免%
    nearResist: 0 #近战物理伤害减免%
    remoteResist: 0 #远程物理伤害减免%
  magical: #魔法属性
    attack: 1954 #攻击
    defence: 1100 #防御
    defencePer: 0 #魔法防御%
    resist: 0 #魔伤减免%
  natureResist: #属性-伤害减免
    风: 0
    地: 0
    水: 0
    火: 0
    无: 0
    圣: 0
    暗: 0
    念: 0
    不死: 0
    毒: 0
  raceResist: #种族-伤害减免
    动物: 0
    人形: 10
    恶魔: 0
    植物: 0
    不死: 0
    无形: 0
    鱼贝: 0
    天使: 0
    昆虫: 0
    龙: 0
