skill:
  record:
    kind: false
    skill: true
team-invitation:
  keep-alive-img: fight-list
  invitation:
    persistent-dir: invitations
    locate-img: invitation-right-bottom
    title-end-img: invitation-title-end
    title-rescue-left-offset: 195
    title-rescue-top-offset: 8
    title-rescue-bottom-offset: 10
    item:
      offset-right: 0
      offset-bottom: 3
      width: 654
      height: 165
    btn-cancel:
      left: 441
      top: 85
      width: 198
      height: 66
    btn-confirm:
      left: 441
      top: 13
      width: 199
      height: 66
    title:
      left: 157
      top: 108
      width: 211
      height: 36
