notification:
  - title: 见面豪礼
    close-img: notification-close-1
  - title: 限时礼包
    close-img: notification-close-2
  - title: 荣耀战场
    close-img: notification-close-3
skill:
  auto-select: true
  detect:
    normal:
      persistent-dir: skill/normal/data
      left-bottom-img: skill/normal/left-bottom
      right-top-img: skill/normal/right-top
      skill-offset:
        left: 1
        right: -1
        top: 1
        bottom: -1
      kind:
        left: 52
        top: 89
        size: 140
        core-size: 105
      title:
        left: 0
        top: 22
        width: 243
        height: 22
      record:
        kind: false
        skill: true
        skip: 1
    elite:
      persistent-dir: skill/elite/data
      left-of-kind-img: skill/elite/left-of-kind
      left-of-kind-offset:
        - 64
        - 110
      skill-offset:
        left: -31
        right: 693
        top: -51
        bottom: 44
      kind:
        left: 22
        top: 12
        size: 120
        core-size: 90
      title:
        left: 154
        top: 21
        width: 200
        height: 24
      record:
        kind: false
        skill: true
        skip: -1
team-invitation:
  keep-alive-img: fight-list
  rescue-min: 1
  invitation:
    persistent-dir: invitation/data
    locate-img: invitation/right-bottom
    title-end-img: invitation/title-end
    item:
      offset-right: 0
      offset-bottom: 1
      width: 615
      height: 154
    btn-cancel:
      left: 414
      top: 80
      width: 187
      height: 62
    btn-confirm:
      left: 414
      top: 11
      width: 187
      height: 62
    title:
      left-in-invitation: 147
      height: 33
      top-offset: 1
      width-offset: 0
      padding-top: 7
      padding-bottom: 9
      rescue-left: 178
